// Code generated by "stringer -type=nodeType"; DO NOT EDIT.

package go_data_routing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[source-1]
	_ = x[sink-2]
	_ = x[splitter-3]
	_ = x[processor-4]
	_ = x[to-5]
	_ = x[consumer-6]
	_ = x[filter-7]
	_ = x[aggregator-8]
	_ = x[mapper-9]
	_ = x[enricher-10]
}

const _nodeType_name = "sourcesinksplitterprocessortoconsumerfilteraggregatormapperenricher"

var _nodeType_index = [...]uint8{0, 6, 10, 18, 27, 29, 37, 43, 53, 59, 67}

func (i nodeType) String() string {
	i -= 1
	if i < 0 || i >= nodeType(len(_nodeType_index)-1) {
		return "nodeType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _nodeType_name[_nodeType_index[i]:_nodeType_index[i+1]]
}
