// Code generated by "stringer -type=nodeType"; DO NOT EDIT.

package go_data_routing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[source-1]
	_ = x[sink-2]
	_ = x[filter-3]
	_ = x[processor-4]
	_ = x[to-5]
	_ = x[wiretap-6]
	_ = x[consumer-7]
}

const _nodeType_name = "sourcesinkfilterprocessortowiretapconsumer"

var _nodeType_index = [...]uint8{0, 6, 10, 16, 25, 27, 34, 42}

func (i nodeType) String() string {
	i -= 1
	if i < 0 || i >= nodeType(len(_nodeType_index)-1) {
		return "nodeType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _nodeType_name[_nodeType_index[i]:_nodeType_index[i+1]]
}
